CREATE TABLE timesheetentries
(
    timesheetentryid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment          VARCHAR(255),
    hoursworked      BIGINT,
    CONSTRAINT pk_timesheetentries PRIMARY KEY (timesheetentryid)
);

CREATE TABLE timesheets
(
    timesheetid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment     VARCHAR(255),
    CONSTRAINT pk_timesheets PRIMARY KEY (timesheetid)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);